### ISSUE TITLE
Can this burp plugin filter some extension files?

### ISSUE THREAD

**Issue by 7e1** [righettod/activity-trail-log#1]
Hi, Can this burp plugin filter some extension files?

Example url:
1. www.example.org/1.png
2. www.example.org/2.svg

**Comment by righettod** [comment]
Hi,

Currently not because the main goal of the extension is to have a full log of all requests send to a target during an assessment but i can add an option in the config menu to excludes images from the logging...

I will add it on the features list for the version **1.0.2**.
